# Generated by Django 4.2.3 on 2023-08-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('fullName', models.CharField(max_length=100)),
                ('handle', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='user')),
                ('role', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
