# Generated by Django 4.2.3 on 2023-11-09 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('physiotherapist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patients_as_physio', to='account.user')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patients', to='account.user')),
            ],
        ),
    ]
