# Generated by Django 4.2.3 on 2023-11-09 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_assignedpatient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedpatient',
            old_name='user_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='assignedpatient',
            old_name='physiotherapist_id',
            new_name='physiotherapist',
        ),
    ]
