# Generated by Django 4.2.3 on 2023-09-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_recordedvideo_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('courseTeacher', models.CharField(max_length=50)),
                ('courseSeason', models.CharField(max_length=10)),
                ('courseKey', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='RecordedVideo',
        ),
    ]
