# Generated by Django 4.2.3 on 2023-10-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_video_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('result', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.CharField(max_length=255)),
            ],
        ),
    ]
